version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  test:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Bundle
          command: bash bin/setup
      - run:
          name: Run tests
          command: bundle exec rspec
  deploy:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Setup Rubygems
          command: bash .circleci/setup-rubygems.sh
      - run:
          name: Publish to Rubygems
          command: |
            gem build nova-api.gemspec
            gem push "nova-api-$(git describe --tags).gem"

workflows:
  version: 2
  test-deploy:
    jobs:
      - test
      - deploy:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/